[phases.setup]
nixPkgs = [
  "tesseract",
  "tesseract-data-eng",
  "opencv",
  "ffmpeg",
  "poppler_utils"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p backend/uploads backend/outputs"
]

[start]
cmd = "cd backend && python app.py" 