services:
  - type: web
    name: parsel-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 